server:
  nodeId: ${hostname:1}
  port: 9094
  accessControlAllowOrigin:
  ssl:
    enabled: false
    key-store:
    key-store-password:

healthcheck:
  maxHeapUsage: 0.8
  minDiskFreeSpace: 2147483648